name: Test tags

on:
  push:
    branches:
      - br1
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print details
        run: |
            echo "started main workflow"
            echo "triggering 2nd one"
      - name: Invoke CI deploy workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          event-type: eventA
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'